/// Workspace build — coordinates compiler-core, compiler-cli and language-server.
///
///   zig build          → builds botopink + botopink-lsp
///   zig build test     → runs every compiler-core test
///   zig build test -Dtest-filter=<substr> → runs only matching tests
///   zig build run      → builds and runs the botopink CLI
const std = @import("std");
const wasm3 = @import("modules/wasm3/build.zig");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    // wasm3 needs libc; on Linux + system glibc 2.42 (Arch as of 2026-06-17)
    // Zig 0.16's linker errors on the new `.sframe` sections in the system
    // crt1.o (`unhandled relocation type R_X86_64_PC64`). The workaround is to
    // use Zig's bundled glibc + crt1, which we opt into by re-resolving the
    // target with an explicit glibc version pin. Affects only Linux-gnu
    // builds; macOS / Windows / musl pass through unchanged.
    const target_for_libc = libcResolvedTarget(b, target);

    // ── std prelude ───────────────────────────────────────────────────────────

    const std_prelude = b.addModule("std_prelude", .{
        .root_source_file = b.path("modules/compiler-core/src/comptime/stdlib/prelude.zig"),
        .target = target,
    });

    // Core controller files flattened into the global type env. These are NOT
    // importable "std" packages — `prelude.zig` embeds them by name, so they are
    // anonymous imports on the std_prelude module.
    const std_core_files = [_][]const u8{
        "primitives.bp",
        "builtins.d.bp",
        "builtins_fns.d.bp",
    };
    for (std_core_files) |f| {
        std_prelude.addAnonymousImport(f, .{
            .root_source_file = b.path(b.fmt("libs/std/src/{s}", .{f})),
        });
    }

    // Compiler-internal `.bp` sources — NOT user-importable (no `pub mod` entry
    // in `root.bp`), NOT flattened into the global type env (no entry in the
    // `pkg_modules` registry above). The wat3 comptime prelude (`template_runtime.bp`)
    // is the first such file: `wat_runtime.zig` reads the embedded source through
    // `std_prelude.template_runtime_src`, compiles it through the wat backend, and
    // splices the post-processed wat into `prelude()` ahead of every template body.
    const std_internal_files = [_][]const u8{
        "template_runtime.bp",
    };
    for (std_internal_files) |f| {
        std_prelude.addAnonymousImport(f, .{
            .root_source_file = b.path(b.fmt("libs/std/src/{s}", .{f})),
        });
    }

    // "std" package modules — importable via `import {…} from "std"`. The set is
    // derived from the std module tree: `libs/std/src/root.bp` declares one
    // `pub mod <name>;` per module, and the build embeds exactly those. This is
    // the std pilot of the explicit module system — `root.bp` is the single
    // source of truth, so adding a module is `drop libs/std/src/<name>.bp` +
    // `pub mod <name>;` in root.bp (no build.zig edit). compiler-core then
    // discovers them generically through the generated `std_pkg` table below, so
    // adding a module never touches `modules/compiler-core/src/**` either.
    // (Application-level libs like `erika` are NOT std — they ship under
    // `libs/<name>/` and load through the generic `from "<lib>"` loader.)
    const std_pkg_files = stdPkgFilesFromRoot(b);
    // Generate the package-module registry (`pkg_modules: [N]{ path, source }`),
    // each entry embedding its `.bp` source. The generated file lives in its own
    // module so its `@embedFile`s resolve against the package `.bp` anonymous
    // imports; `std_prelude` re-exports the table for compiler-core to consume.
    var pkg_table_src: []const u8 =
        "// Generated by build.zig — do not edit. The \"std\" package registry.\n" ++
        "pub const pkg_modules = [_]struct { path: []const u8, source: []const u8 }{\n";
    for (std_pkg_files) |f| {
        const name = f[0 .. f.len - ".bp".len];
        pkg_table_src = b.fmt(
            "{s}    .{{ .path = \"std/{s}\", .source = @embedFile(\"{s}\") }},\n",
            .{ pkg_table_src, name, f },
        );
    }
    pkg_table_src = b.fmt("{s}}};\n", .{pkg_table_src});

    const wf = b.addWriteFiles();
    const pkg_table_file = wf.add("std_pkg_modules.zig", pkg_table_src);
    const std_pkg = b.createModule(.{
        .root_source_file = pkg_table_file,
        .target = target,
    });
    for (std_pkg_files) |f| {
        std_pkg.addAnonymousImport(f, .{
            .root_source_file = b.path(b.fmt("libs/std/src/{s}", .{f})),
        });
    }
    std_prelude.addImport("std_pkg", std_pkg);

    // ── compiler-core (library) ───────────────────────────────────────────────

    const core_mod = b.addModule("botopink", .{
        .root_source_file = b.path("modules/compiler-core/src/root.zig"),
        .target = target,
        .imports = &.{
            .{ .name = "std_prelude", .module = std_prelude },
        },
    });
    // wasm3 headers are accessed via `@cImport` in
    // `comptime/runtime/wasm3_host.zig`. The header path resolution is
    // module-scoped, so it must be set on `core_mod` even when the C sources
    // are only linked into downstream Compile targets via `wasm3.link`.
    wasm3.exposeHeaders(b, core_mod);

    // ── compiler-core tests ───────────────────────────────────────────────────

    const core_test_mod = b.addModule("botopink_tests", .{
        .root_source_file = b.path("modules/compiler-core/src/test_root.zig"),
        .target = target_for_libc,
        .imports = &.{
            .{ .name = "std_prelude", .module = std_prelude },
        },
    });

    const test_filters = b.option([]const []const u8, "test-filter", "Only run tests matching filter") orelse &.{};
    const core_tests = b.addTest(.{
        .root_module = core_test_mod,
        .filters = test_filters,
    });

    wasm3.link(b, core_tests);

    const run_core_tests = b.addRunArtifact(core_tests);
    // Ensure snapshots are written inside modules/compiler-core/,
    // not at the workspace root.
    run_core_tests.setCwd(b.path("modules/compiler-core"));

    // `clean-tmp` reaps per-test scratch dirs older than 1 day from
    // `<compiler-core>/.botopinkbuild/tmp/`. A live test run never
    // touches another run's dirs (1-day TTL) so the reap is safe
    // alongside parallel `zig build test` invocations. `mkdir -p`
    // makes the step idempotent on a fresh clone where the tmp root
    // hasn't been created yet.
    const clean_tmp_run = b.addSystemCommand(&.{
        "sh", "-c",
        "mkdir -p .botopinkbuild/tmp && find .botopinkbuild/tmp -mindepth 1 -maxdepth 1 -type d -mtime +1 -exec rm -rf {} +",
    });
    clean_tmp_run.setCwd(b.path("modules/compiler-core"));
    clean_tmp_run.has_side_effects = true; // never cache — always re-reap

    const clean_tmp_step = b.step("clean-tmp", "Reap per-test scratch dirs older than 1 day from .botopinkbuild/tmp/");
    clean_tmp_step.dependOn(&clean_tmp_run.step);

    // Runs at the start of every test cycle so crashed-test leaks
    // never accumulate beyond a day.
    run_core_tests.step.dependOn(&clean_tmp_run.step);

    const test_step = b.step("test", "Run every test (compiler-core + language-server)");
    test_step.dependOn(&run_core_tests.step);

    // ── lib-agnostic gate (annotation-processors P0) ──────────────────────────
    // HARD RULE: the compiler core must name no specific NON-std library. Fail
    // the build if any framework name leaks into `modules/compiler-core/src`.
    // `std` is the one allowed exception (deliberately absent from the
    // alternation). Extend the pattern as frameworks are added. `grep` exits 1
    // when nothing matches, so `!` turns "clean" into success; a match → exit 0
    // → `!` → failure. This file lives outside the scanned tree, so it may name
    // the forbidden tokens. Runs as part of `zig build test`.
    const lib_agnostic_gate = b.addSystemCommand(&.{
        "sh",                                                             "-c",
        "! grep -riIE 'rakun|jhonstart|erika' modules/compiler-core/src",
    });
    lib_agnostic_gate.has_side_effects = true; // never cache — always re-scan
    test_step.dependOn(&lib_agnostic_gate.step);

    // ── language-server tests ─────────────────────────────────────────────────

    const lsp_test_mod = b.createModule(.{
        .root_source_file = b.path("modules/language-server/src/test_root.zig"),
        .target = target_for_libc,
        .imports = &.{
            .{ .name = "botopink", .module = core_mod },
        },
    });

    const lsp_tests = b.addTest(.{ .root_module = lsp_test_mod, .filters = test_filters });
    wasm3.link(b, lsp_tests);
    const run_lsp_tests = b.addRunArtifact(lsp_tests);
    run_lsp_tests.setCwd(b.path("modules/language-server"));

    test_step.dependOn(&run_lsp_tests.step);

    // ── compiler-cli tests ────────────────────────────────────────────────────
    // Rooted at the CLI entry so every `test {}` reachable through its import
    // graph runs (scanner/resolver/libs source-loading logic).

    const cli_test_mod = b.createModule(.{
        .root_source_file = b.path("modules/compiler-cli/src/main.zig"),
        .target = target_for_libc,
        .imports = &.{
            .{ .name = "botopink", .module = core_mod },
        },
    });

    const cli_tests = b.addTest(.{ .root_module = cli_test_mod, .filters = test_filters });
    wasm3.link(b, cli_tests);
    const run_cli_tests = b.addRunArtifact(cli_tests);
    run_cli_tests.setCwd(b.path("modules/compiler-cli"));

    test_step.dependOn(&run_cli_tests.step);

    // ── compiler-cli (botopink executable) ────────────────────────────────────

    const cli_exe = b.addExecutable(.{
        .name = "botopink",
        .root_module = b.createModule(.{
            .root_source_file = b.path("modules/compiler-cli/src/main.zig"),
            .target = target_for_libc,
            .optimize = optimize,
            .imports = &.{
                .{ .name = "botopink", .module = core_mod },
            },
        }),
    });
    wasm3.link(b, cli_exe);

    b.installArtifact(cli_exe);

    // ── language-server (botopink-lsp executable) ─────────────────────────────

    const lsp_exe = b.addExecutable(.{
        .name = "botopink-lsp",
        .root_module = b.createModule(.{
            .root_source_file = b.path("modules/language-server/src/main.zig"),
            .target = target_for_libc,
            .optimize = optimize,
            .imports = &.{
                .{ .name = "botopink", .module = core_mod },
            },
        }),
    });
    wasm3.link(b, lsp_exe);

    b.installArtifact(lsp_exe);

    // ── lib-test-runner (botopink-lib-test executable) ────────────────────────
    // Fully self-contained orchestrator — shells out to the installed `botopink`
    // binary, so it carries no `compiler-core` import.

    const lib_test_exe = b.addExecutable(.{
        .name = "botopink-lib-test",
        .root_module = b.createModule(.{
            .root_source_file = b.path("modules/lib-test-runner/src/main.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });

    b.installArtifact(lib_test_exe);

    // ── bpmp (Boto Pink Package Manager executable) ───────────────────────────
    // Self-contained — no `compiler-core` import. bpmp *spawns* `botopink`, it
    // does not link it. Same idea as `lib-test-runner`: a thin orchestrator that
    // calls out to the toolchain rather than embedding it.

    const bpmp_mod = b.createModule(.{
        .root_source_file = b.path("modules/bpmp/src/main.zig"),
        .target = target,
        .optimize = optimize,
    });
    const bpmp_exe = b.addExecutable(.{ .name = "bpmp", .root_module = bpmp_mod });
    b.installArtifact(bpmp_exe);

    // `zig build test-bpmp` — run bpmp's unit tests. Like `test-libs`/
    // `test-vscode`, kept OUT of `zig build test` until the suite stabilises
    // (the network surface needs hermetic-server fixtures that aren't in tree
    // yet). Pure-fn tests (semver, manifest, lockfile, sha256, storage, …) run
    // here unconditionally.
    const bpmp_test_mod = b.createModule(.{
        .root_source_file = b.path("modules/bpmp/src/main.zig"),
        .target = target,
    });
    const bpmp_tests = b.addTest(.{ .root_module = bpmp_test_mod, .filters = test_filters });
    const run_bpmp_tests = b.addRunArtifact(bpmp_tests);
    run_bpmp_tests.setCwd(b.path("modules/bpmp"));
    const test_bpmp_step = b.step("test-bpmp", "Run the bpmp unit tests");
    test_bpmp_step.dependOn(&run_bpmp_tests.step);

    // `zig build test-libs` — run every lib's tests on each backend via the
    // shipped `scripts/test-libs.sh` wrapper. The wrapper pre-flights
    // node/escript/erlc/wasmtime (K1 of v0.beta.19 §K env deferreds) so a
    // missing backend runtime surfaces as a clear warning before the runner
    // bails. Forwards `--` args, e.g.
    //   zig build test-libs -- --target erlang --lib rakun
    // Depends on the `botopink` install so `zig-out/bin/botopink-lib-test`
    // exists when the wrapper exec's it. Deliberately NOT wired into
    // `zig build test`.
    //
    // Path note (ci-pipelines-green): the wrapper is shipped INSIDE the
    // botopink-lang tree so `zig build test-libs` works in both the meta
    // workspace layout (`<meta>/repository/botopink-lang/`) and the
    // standalone lib-checkout layout (`<lib>/botopink-lang/`) without the
    // sibling lib workflows needing extra steps to stage it.
    const test_libs_run = b.addSystemCommand(&.{ "bash", "scripts/test-libs.sh" });
    test_libs_run.step.dependOn(b.getInstallStep());
    test_libs_run.setCwd(b.path("."));
    test_libs_run.has_side_effects = true; // spawns child compilers — never cache
    if (b.args) |args| test_libs_run.addArgs(args);

    const test_libs_step = b.step("test-libs", "Run every libs/ project's tests per backend");
    test_libs_step.dependOn(&test_libs_run.step);

    // `zig build test-vscode` — run the VS Code extension's pure-function
    // unit suite (`npm test` → tsc typecheck + Node's built-in test runner)
    // via the workspace's `scripts/test-vscode.sh` wrapper. On first run the
    // wrapper does an `npm ci` (K2 of v0.beta.19 §K env deferreds) and
    // touches a marker under `repository/vscode-extension/node_modules/`;
    // subsequent runs skip the install. Like `test-libs`, NOT wired into
    // `zig build test` — needs `node`/`npm` on PATH.
    const test_vscode_run = b.addSystemCommand(&.{ "bash", "../../scripts/test-vscode.sh" });
    test_vscode_run.setCwd(b.path("."));
    test_vscode_run.has_side_effects = true; // spawns node — never cache

    const test_vscode_step = b.step("test-vscode", "Run the VS Code extension unit tests");
    test_vscode_step.dependOn(&test_vscode_run.step);

    // `zig build test-backends` — the single build step that reaches BEAM + wasm
    // *execution* (not just codegen snapshots): builds the CLI, then runs the
    // backend-execution harness against `node`/`escript`/`erlc`+`erl`/`wasmtime`,
    // skipping any backend whose runtime is absent. Like `test-libs`/`test-vscode`
    // it is NOT wired into `zig build test` (needs those runtimes on PATH).
    // BOTOPINK_SKIP_BUILD=1 avoids nesting a `zig build` — the CLI is installed by
    // the dependency below.
    const test_backends_run = b.addSystemCommand(&.{ "bash", "modules/compiler-cli/tests/backend_exec.sh" });
    test_backends_run.setCwd(b.path("."));
    test_backends_run.setEnvironmentVariable("BOTOPINK_SKIP_BUILD", "1");
    test_backends_run.step.dependOn(b.getInstallStep());
    test_backends_run.has_side_effects = true; // spawns child runtimes — never cache

    const test_backends_step = b.step("test-backends", "Run beam/wasm/erlang execution parity scenarios");
    test_backends_step.dependOn(&test_backends_run.step);

    // ── Run step ──────────────────────────────────────────────────────────────

    const run_cmd = b.addRunArtifact(cli_exe);
    run_cmd.step.dependOn(b.getInstallStep());
    if (b.args) |args| run_cmd.addArgs(args);

    const run_step = b.step("run", "Build and run the botopink CLI");
    run_step.dependOn(&run_cmd.step);
}

/// Re-resolve the user-requested target with an explicit bundled-glibc version
/// when the resolved native target points at a `linux-gnu` system. This sidesteps
/// the Zig 0.16 + glibc ≥ 2.41 `.sframe` crt1.o relocation bug by making Zig
/// emit its own crt files instead of dragging the system ones. macOS, Windows,
/// musl and any explicitly-pinned target pass through unchanged.
fn libcResolvedTarget(b: *std.Build, requested: std.Build.ResolvedTarget) std.Build.ResolvedTarget {
    const r = requested.result;
    if (r.os.tag != .linux) return requested;
    if (r.abi != .gnu) return requested;
    var q = requested.query;
    if (q.glibc_version != null) return requested;
    q.glibc_version = .{ .major = 2, .minor = 38, .patch = 0 };
    return b.resolveTargetQuery(q);
}

/// Derive the importable "std" package module files from the std module tree
/// (`libs/std/src/root.bp`): one `<name>.bp` per `pub mod <name>;` declaration,
/// in declaration order. This makes `root.bp` the single source of truth for the
/// std module set (the module-system pilot for std). Panics with a clear message
/// if the root is missing or declares nothing — a misread here would silently
/// drop std modules and break every build.
fn stdPkgFilesFromRoot(b: *std.Build) []const []const u8 {
    const root_src = b.build_root.handle.readFileAlloc(
        b.graph.io,
        "libs/std/src/root.bp",
        b.allocator,
        .unlimited,
    ) catch |err| std.debug.panic(
        "std pilot: cannot read libs/std/src/root.bp (the std module-tree root): {s}",
        .{@errorName(err)},
    );

    var files: std.ArrayListUnmanaged([]const u8) = .empty;
    var it = std.mem.splitScalar(u8, root_src, '\n');
    while (it.next()) |raw| {
        var line = std.mem.trim(u8, raw, " \t\r");
        // Skip comments and blank lines; accept `mod X;` and `pub mod X;`.
        if (std.mem.startsWith(u8, line, "//")) continue;
        if (std.mem.startsWith(u8, line, "pub ")) line = std.mem.trimStart(u8, line["pub ".len..], " \t");
        if (!std.mem.startsWith(u8, line, "mod ")) continue;
        var name = std.mem.trim(u8, line["mod ".len..], " \t");
        name = std.mem.trimEnd(u8, name, ";");
        name = std.mem.trim(u8, name, " \t");
        if (name.len == 0) continue;
        files.append(b.allocator, b.fmt("{s}.bp", .{name})) catch @panic("OOM");
    }

    if (files.items.len == 0) std.debug.panic(
        "std pilot: libs/std/src/root.bp declares no `pub mod` modules",
        .{},
    );
    return files.toOwnedSlice(b.allocator) catch @panic("OOM");
}
