/// Workspace build — coordinates compiler-core, compiler-cli and language-server.
///
///   zig build          → builds botopink + botopink-lsp
///   zig build test     → runs every compiler-core, language-server, CLI, lib-test-runner and manifest unit test
///   zig build test -Dtest-filter=<substr> → runs only matching tests
///   zig build test-cli → runs every modules/compiler-cli/tests/*.sh end to end
///   zig build test-libs → compiles and tests every visible `.bp` library per target
///   zig build run      → builds and runs the botopink CLI
const std = @import("std");
const wasm3 = @import("modules/wasm3/build.zig");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    // On Linux + system glibc 2.41 or newer (Arch as of 2026-06-17) Zig 0.16's
    // linker errors on the new `.sframe` sections in the system crt1.o
    // (`unhandled relocation type R_X86_64_PC64`). The workaround is to use
    // Zig's bundled glibc + crt1, which we opt into by re-resolving the target
    // with an explicit glibc version pin. Affects only Linux-gnu builds;
    // macOS / Windows / musl pass through unchanged.
    const target_for_libc = libcResolvedTarget(b, target);

    // ── std prelude ───────────────────────────────────────────────────────────

    // "std" package modules — importable via `import {…} from "std"`. The set is
    // derived from the std module tree: `libs/std/src/root.bp` declares one
    // `pub mod <name>;` per module, and the build embeds exactly those. This is
    // the std pilot of the explicit module system — `root.bp` is the single
    // source of truth, so adding a module is `drop libs/std/src/<name>.bp` +
    // `pub mod <name>;` in root.bp (no build.zig edit); a `pub mod <dir>;`
    // whose `<dir>/mod.bp` declares its own `pub mod`s embeds those under
    // `std/<dir>/<name>` (decision 106's `io/`, `testing/`). compiler-core then
    // discovers them generically through the generated `std_pkg` table below, so
    // adding a module never touches `modules/compiler-core/src/**` either.
    // (Application-level libs like `erika` are NOT std — they ship under
    // `libs/<name>/` and load through the generic `from "<lib>"` loader.)
    const std_pkg_files = stdPkgFilesFromRoot(b);
    // Generate the package-module registry (`pkg_modules: [N]{ path, source }`),
    // each entry embedding its `.bp` source. The generated file lives in its own
    // module so its `@embedFile`s resolve against the package `.bp` anonymous
    // imports; `std_prelude` re-exports the table for compiler-core to consume.
    var pkg_table_src: []const u8 =
        "// Generated by build.zig — do not edit. The \"std\" package registry.\n" ++
        "pub const pkg_modules = [_]struct { path: []const u8, source: []const u8 }{\n";
    for (std_pkg_files) |f| {
        // `f` is relative to `libs/std/src` (`dict.bp`, `io/fs.bp`); the
        // registry key is the same path without the extension, under `std/`.
        const name = f[0 .. f.len - ".bp".len];
        pkg_table_src = b.fmt(
            "{s}    .{{ .path = \"std/{s}\", .source = @embedFile(\"{s}\") }},\n",
            .{ pkg_table_src, name, f },
        );
    }
    pkg_table_src = b.fmt("{s}}};\n", .{pkg_table_src});

    // The bundled packages (decisions 115–117): libraries shipped INSIDE the
    // compiler and imported by name with no `dependencies` entry, the way `std`
    // is. `bundled_packages` is the one list of their names — nothing else in
    // the toolchain spells one. `std` keeps its own embedding above (its module
    // tree, the ambient core files); every other name is `libs/<name>/`, whose
    // `botopink.json` `files` are embedded as `<name>/<stem>` modules. A
    // bundled library ships `.bp` files only (decision 117 rule 8): a `files`
    // entry that is not `.bp` stops the build.
    const bundled = bundledPkgFiles(b);
    pkg_table_src = b.fmt(
        "{s}\n/// The bundled packages, `std` first (its modules are `pkg_modules` above).\n" ++
            "pub const BundledModule = struct {{ stem: []const u8, file: []const u8, source: []const u8 }};\n" ++
            "pub const BundledPackage = struct {{ name: []const u8, modules: []const BundledModule }};\n" ++
            "pub const bundled_packages = [_]BundledPackage{{\n    .{{ .name = \"std\", .modules = &.{{}} }},\n",
        .{pkg_table_src},
    );
    for (bundled) |pkg| {
        pkg_table_src = b.fmt("{s}    .{{ .name = \"{s}\", .modules = &.{{\n", .{ pkg_table_src, pkg.name });
        for (pkg.files) |f| {
            pkg_table_src = b.fmt(
                "{s}        .{{ .stem = \"{s}\", .file = \"{s}\", .source = @embedFile(\"{s}/{s}\") }},\n",
                .{ pkg_table_src, f[0 .. f.len - ".bp".len], f, pkg.name, f },
            );
        }
        pkg_table_src = b.fmt("{s}    }} }},\n", .{pkg_table_src});
    }
    pkg_table_src = b.fmt("{s}}};\n", .{pkg_table_src});

    const wf = b.addWriteFiles();
    const pkg_table_file = wf.add("std_pkg_modules.zig", pkg_table_src);
    const std_prelude = stdPreludeModule(b, target, std_pkg_files, pkg_table_file);

    const test_filters = b.option([]const []const u8, "test-filter", "Only run tests matching filter") orelse &.{};

    // ── test_scratch (per-process scratch paths) ──────────────────────────────
    // Every test binary below runs with its package directory as cwd, so the
    // whole suite writes into ONE shared checkout. A scratch path scoped per
    // test name but not per RUN is shared with every other process running the
    // suite, and each test empties its own root on the way in — so a second
    // `zig build test` over the same checkout reds the first. This module is
    // the one way a test spells such a path; its root carries a per-process
    // segment. See `modules/test-scratch/src/root.zig`.
    //
    // It is given to the TEST modules ONLY. Naming it outside a `test` block
    // is analysed by the executable build too, where the module does not
    // exist — so it does not compile. That is the refusal (decision 67).
    const test_scratch_mod = b.addModule("test_scratch", .{
        .root_source_file = b.path("modules/test-scratch/src/root.zig"),
        .target = target,
    });
    const test_scratch_tests = b.addTest(.{
        .root_module = b.createModule(.{
            .root_source_file = b.path("modules/test-scratch/src/root.zig"),
            .target = target,
        }),
        .filters = test_filters,
    });
    const run_test_scratch_tests = b.addRunArtifact(test_scratch_tests);
    // Its own tests write a scratch tree — under its own package directory.
    run_test_scratch_tests.setCwd(b.path("modules/test-scratch"));

    // ── manifest (shared `botopink.json` model) ───────────────────────────────
    // The one reading of the manifest — packages, workspaces, the dependency
    // object — imported by the CLI, the LSP, the lib-test runner and bpmp.
    // `std` only: the runner and bpmp keep their "no compiler-core" contract.

    const manifest_mod = b.addModule("manifest", .{
        .root_source_file = b.path("modules/manifest/src/root.zig"),
        .target = target,
    });
    const manifest_tests = b.addTest(.{
        .root_module = b.createModule(.{
            .root_source_file = b.path("modules/manifest/src/root.zig"),
            .target = target,
        }),
        .filters = test_filters,
    });
    const run_manifest_tests = b.addRunArtifact(manifest_tests);
    // Fixtures under modules/manifest/tests/fixtures are read relative to cwd.
    run_manifest_tests.setCwd(b.path("modules/manifest"));

    // ── compiler-core (library) ───────────────────────────────────────────────

    const core_mod = b.addModule("botopink", .{
        .root_source_file = b.path("modules/compiler-core/src/root.zig"),
        .target = target,
        .imports = &.{
            .{ .name = "std_prelude", .module = std_prelude },
        },
    });
    // ── compiler-core tests ───────────────────────────────────────────────────

    const core_test_mod = b.addModule("botopink_tests", .{
        .root_source_file = b.path("modules/compiler-core/src/test_root.zig"),
        .target = target_for_libc,
        .imports = &.{
            .{ .name = "std_prelude", .module = std_prelude },
            .{ .name = "test_scratch", .module = test_scratch_mod },
        },
    });

    // ── resident comptime modules: `.erl` → `erlc` → `.beam`, embedded ───────
    // Decision 83 (front 18 step 1c): the comptime node's server and its two
    // preludes are compiled by `erlc` HERE, once per source change, and reach
    // `comptime/runtime/persistent_erl.zig` as `@embedFile`s — so `erlc` is a
    // dependency of building the compiler and of nothing a user runs. The
    // renderer runs on the HOST (a cross-build still renders here), so it gets
    // a host-targeted `std_prelude`; `erlc` must be on PATH (OTP 28+, the
    // floor decision 86 pins), or this step fails the build — deliberately.
    //
    // The renderer's imports reach `codegen/`, so its module root has to be
    // compiler-core's `src/`: the tree's `.zig` files are copied into the cache
    // with a one-line root beside them, and nothing is added to the source tree
    // for the tool's sake.
    const render_tree = b.addWriteFiles();
    _ = render_tree.addCopyDirectory(b.path("modules/compiler-core/src"), "src", .{ .include_extensions = &.{".zig"} });
    const render_root = render_tree.add(
        "src/render_resident_main.zig",
        "pub const main = @import(\"comptime/runtime/render_resident.zig\").main;\n",
    );
    const render_resident = b.addExecutable(.{
        .name = "render-resident",
        .root_module = b.createModule(.{
            .root_source_file = render_root,
            .target = b.graph.host,
            .imports = &.{
                .{ .name = "std_prelude", .module = stdPreludeModule(b, b.graph.host, std_pkg_files, pkg_table_file) },
            },
        }),
    });
    const render_run = b.addRunArtifact(render_resident);
    const resident_erl = render_run.addOutputDirectoryArg("resident-erl");
    const erlc_run = b.addSystemCommand(&.{ "erlc", "+deterministic", "-o" });
    const resident_beam = erlc_run.addOutputDirectoryArg("resident-beam");
    const resident_modules = [_][]const u8{ "botopink_comptime_server", "bp_comptime_template", "bp_comptime_decorator" };
    for (resident_modules) |m| erlc_run.addFileArg(resident_erl.path(b, b.fmt("{s}.erl", .{m})));
    for ([_]*std.Build.Module{ core_mod, core_test_mod }) |mod| {
        for (resident_modules) |m| {
            mod.addAnonymousImport(b.fmt("{s}.beam", .{m}), .{
                .root_source_file = resident_beam.path(b, b.fmt("{s}.beam", .{m})),
            });
        }
    }

    // ── the wat comptime runtime: `rt.zig` → `bp_wat_rt.wasm`, embedded ──────
    // Front 18 step 2. The term library a lowered comptime body links against
    // (`comptime/runtime/wat/link.zig`) is compiled here for `wasm32-freestanding`
    // at the MVP feature set wasm3 and every browser run, and reaches
    // `wat/program.zig` as an `@embedFile` — in the native compiler and in the
    // browser build alike. `__heap_base` is exported so the linker knows where
    // the runtime's static memory (`.bss` included) ends.
    const wat_rt = b.addExecutable(.{
        .name = "bp_wat_rt",
        .root_module = b.createModule(.{
            .root_source_file = b.path("modules/compiler-core/src/comptime/runtime/wat/rt.zig"),
            .target = b.resolveTargetQuery(.{
                .cpu_arch = .wasm32,
                .os_tag = .freestanding,
                .cpu_model = .{ .explicit = &std.Target.wasm.cpu.mvp },
            }),
            .optimize = .ReleaseSmall,
        }),
    });
    wat_rt.entry = .disabled;
    wat_rt.rdynamic = true;
    wat_rt.root_module.export_symbol_names = &.{"__heap_base"};
    for ([_]*std.Build.Module{ core_mod, core_test_mod }) |mod| {
        mod.addAnonymousImport("bp_wat_rt.wasm", .{ .root_source_file = wat_rt.getEmittedBin() });
    }
    // wasm3 runs it in-process on every native build (`persistent_wat.zig`).
    wasm3.exposeHeaders(b, core_mod);
    wasm3.exposeHeaders(b, core_test_mod);

    const core_tests = b.addTest(.{
        .root_module = core_test_mod,
        .filters = test_filters,
    });
    wasm3.link(b, core_tests);

    const run_core_tests = b.addRunArtifact(core_tests);
    // Ensure snapshots are written inside modules/compiler-core/,
    // not at the workspace root.
    run_core_tests.setCwd(b.path("modules/compiler-core"));

    // `clean-tmp` reaps per-test scratch dirs older than 1 day from
    // `<compiler-core>/.botopinkbuild/tmp/`. A live test run never
    // touches another run's dirs (1-day TTL) so the reap is safe
    // alongside parallel `zig build test` invocations. `mkdir -p`
    // makes the step idempotent on a fresh clone where the tmp root
    // hasn't been created yet.
    const clean_tmp_run = b.addSystemCommand(&.{
        "sh",                                                                                                                 "-c",
        "mkdir -p .botopinkbuild/tmp && find .botopinkbuild/tmp -mindepth 1 -maxdepth 1 -type d -mtime +1 -exec rm -rf {} +",
    });
    clean_tmp_run.setCwd(b.path("modules/compiler-core"));
    clean_tmp_run.has_side_effects = true; // never cache — always re-reap

    // The same reap for the per-PROCESS roots `test_scratch` draws, which every
    // package's test binary leaves behind in its own directory
    // (`modules/<pkg>/.botopinkbuild/test-scratch/<id>/`). A test removes its
    // own subtree on the way out, so what survives is an empty root — one per
    // run, and one per crashed run with its fixtures still in it. Same 1-day
    // TTL, for the same reason: a live run's root is minutes old, never a day.
    const clean_scratch_run = b.addSystemCommand(&.{
        "sh",                                                                                                               "-c",
        "find modules -mindepth 4 -maxdepth 4 -type d -path '*/.botopinkbuild/test-scratch/*' -mtime +1 -exec rm -rf {} +",
    });
    clean_scratch_run.has_side_effects = true; // never cache — always re-reap

    const clean_tmp_step = b.step("clean-tmp", "Reap per-test scratch dirs older than 1 day (.botopinkbuild/tmp/ and every .botopinkbuild/test-scratch/)");
    clean_tmp_step.dependOn(&clean_tmp_run.step);
    clean_tmp_step.dependOn(&clean_scratch_run.step);

    // Runs at the start of every test cycle so crashed-test leaks
    // never accumulate beyond a day.
    run_core_tests.step.dependOn(&clean_tmp_run.step);
    run_core_tests.step.dependOn(&clean_scratch_run.step);

    const test_step = b.step("test", "Run every unit test (compiler-core, language-server, CLI, lib-test-runner, manifest, test-scratch)");
    test_step.dependOn(&run_core_tests.step);
    test_step.dependOn(&run_manifest_tests.step);
    test_step.dependOn(&run_test_scratch_tests.step);

    // ── shared-checkout gate (front 00 · 11-tooling) ──────────────────────────
    // HARD RULE: a test may not name a cwd-anchored `.botopinkbuild` path. Each
    // test binary runs with its package directory as cwd, so a fixed path is
    // shared with every other process running the suite and the second one
    // deletes the first one's fixtures mid-test. The one way to spell such a
    // path is the `test_scratch` module, whose root is per process. The script
    // refuses, it does not warn, and no flag turns it off (decision 67).
    const test_scratch_gate = b.addSystemCommand(&.{"scripts/check-test-scratch.sh"});
    test_scratch_gate.has_side_effects = true; // never cache — always re-scan
    test_step.dependOn(&test_scratch_gate.step);

    // ── lib-agnostic gate (annotation-processors P0) ──────────────────────────
    // HARD RULE: the compiler core must name no specific NON-std library. Fail
    // the build if any framework name leaks into `modules/compiler-core/src`.
    // `std` is the one allowed exception (deliberately absent from the
    // alternation). Extend the pattern as frameworks are added. `grep` exits 1
    // when nothing matches, so `!` turns "clean" into success; a match → exit 0
    // → `!` → failure. This file lives outside the scanned tree, so it may name
    // the forbidden tokens. Runs as part of `zig build test`.
    const lib_agnostic_gate = b.addSystemCommand(&.{
        "sh",                                                             "-c",
        "! grep -riIE 'rakun|jhonstart|erika' modules/compiler-core/src",
    });
    lib_agnostic_gate.has_side_effects = true; // never cache — always re-scan
    test_step.dependOn(&lib_agnostic_gate.step);

    // ── language-server tests ─────────────────────────────────────────────────

    const lsp_test_mod = b.createModule(.{
        .root_source_file = b.path("modules/language-server/src/test_root.zig"),
        .target = target_for_libc,
        .imports = &.{
            .{ .name = "botopink", .module = core_mod },
            .{ .name = "manifest", .module = manifest_mod },
            .{ .name = "test_scratch", .module = test_scratch_mod },
        },
    });

    const lsp_tests = b.addTest(.{ .root_module = lsp_test_mod, .filters = test_filters });
    wasm3.link(b, lsp_tests);

    const run_lsp_tests = b.addRunArtifact(lsp_tests);
    run_lsp_tests.setCwd(b.path("modules/language-server"));

    test_step.dependOn(&run_lsp_tests.step);

    // ── compiler-cli tests ────────────────────────────────────────────────────
    // Rooted at the CLI entry so every `test {}` reachable through its import
    // graph runs (scanner/resolver/libs source-loading logic).

    const cli_test_mod = b.createModule(.{
        .root_source_file = b.path("modules/compiler-cli/src/main.zig"),
        .target = target_for_libc,
        .imports = &.{
            .{ .name = "botopink", .module = core_mod },
            .{ .name = "manifest", .module = manifest_mod },
            .{ .name = "test_scratch", .module = test_scratch_mod },
        },
    });

    const cli_tests = b.addTest(.{ .root_module = cli_test_mod, .filters = test_filters });
    wasm3.link(b, cli_tests);

    const run_cli_tests = b.addRunArtifact(cli_tests);
    run_cli_tests.setCwd(b.path("modules/compiler-cli"));

    test_step.dependOn(&run_cli_tests.step);

    // ── compiler-cli (botopink executable) ────────────────────────────────────

    const cli_exe = b.addExecutable(.{
        .name = "botopink",
        .root_module = b.createModule(.{
            .root_source_file = b.path("modules/compiler-cli/src/main.zig"),
            .target = target_for_libc,
            .optimize = optimize,
            .imports = &.{
                .{ .name = "botopink", .module = core_mod },
                .{ .name = "manifest", .module = manifest_mod },
            },
        }),
    });

    wasm3.link(b, cli_exe);
    b.installArtifact(cli_exe);

    // ── language-server (botopink-lsp executable) ─────────────────────────────

    const lsp_exe = b.addExecutable(.{
        .name = "botopink-lsp",
        .root_module = b.createModule(.{
            .root_source_file = b.path("modules/language-server/src/main.zig"),
            .target = target_for_libc,
            .optimize = optimize,
            .imports = &.{
                .{ .name = "botopink", .module = core_mod },
                .{ .name = "manifest", .module = manifest_mod },
            },
        }),
    });

    wasm3.link(b, lsp_exe);
    b.installArtifact(lsp_exe);

    // ── lib-test-runner (botopink-lib-test executable) ────────────────────────
    // Fully self-contained orchestrator — shells out to the installed `botopink`
    // binary, so it carries no `compiler-core` import (only the std-only
    // `manifest` module, for the shared reading of `botopink.json`).

    const lib_test_exe = b.addExecutable(.{
        .name = "botopink-lib-test",
        .root_module = b.createModule(.{
            .root_source_file = b.path("modules/lib-test-runner/src/main.zig"),
            .target = target,
            .optimize = optimize,
            .imports = &.{
                .{ .name = "manifest", .module = manifest_mod },
            },
        }),
    });

    b.installArtifact(lib_test_exe);

    // Its unit tests (args, discovery, matrix, runner) run with `zig build test`.
    const lib_test_tests = b.addTest(.{
        .root_module = b.createModule(.{
            .root_source_file = b.path("modules/lib-test-runner/src/main.zig"),
            .target = target,
            .imports = &.{
                .{ .name = "manifest", .module = manifest_mod },
                .{ .name = "test_scratch", .module = test_scratch_mod },
            },
        }),
        .filters = test_filters,
    });
    const run_lib_test_tests = b.addRunArtifact(lib_test_tests);
    run_lib_test_tests.setCwd(b.path("modules/lib-test-runner"));
    test_step.dependOn(&run_lib_test_tests.step);

    // ── bpmp (Boto Pink Package Manager executable) ───────────────────────────
    // Self-contained — no `compiler-core` import. bpmp *spawns* `botopink`, it
    // does not link it. Same idea as `lib-test-runner`: a thin orchestrator that
    // calls out to the toolchain rather than embedding it.

    const bpmp_mod = b.createModule(.{
        .root_source_file = b.path("modules/bpmp/src/main.zig"),
        .target = target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "manifest", .module = manifest_mod },
        },
    });
    const bpmp_exe = b.addExecutable(.{ .name = "bpmp", .root_module = bpmp_mod });
    b.installArtifact(bpmp_exe);

    // `zig build test-bpmp` — run bpmp's unit tests. Like `test-libs`/
    // `test-vscode`, kept OUT of `zig build test` until the suite stabilises
    // (the network surface needs hermetic-server fixtures that aren't in tree
    // yet). Pure-fn tests (semver, manifest, lockfile, sha256, storage, …) run
    // here unconditionally.
    const bpmp_test_mod = b.createModule(.{
        .root_source_file = b.path("modules/bpmp/src/main.zig"),
        .target = target,
        .imports = &.{
            .{ .name = "manifest", .module = manifest_mod },
            .{ .name = "test_scratch", .module = test_scratch_mod },
        },
    });
    const bpmp_tests = b.addTest(.{ .root_module = bpmp_test_mod, .filters = test_filters });
    const run_bpmp_tests = b.addRunArtifact(bpmp_tests);
    run_bpmp_tests.setCwd(b.path("modules/bpmp"));
    const test_bpmp_step = b.step("test-bpmp", "Run the bpmp unit tests");
    test_bpmp_step.dependOn(&run_bpmp_tests.step);

    // `zig build test-libs` — run every lib's tests on each backend via the
    // shipped `scripts/test-libs.sh` wrapper. The wrapper pre-flights
    // node/escript/erlc/wasmtime (K1 of v0.beta.19 §K env deferreds) so a
    // missing backend runtime surfaces as a clear warning before the runner
    // bails. Forwards `--` args, e.g.
    //   zig build test-libs -- --target erlang --lib rakun
    // Depends on the `botopink` install so `zig-out/bin/botopink-lib-test`
    // exists when the wrapper exec's it. Deliberately NOT wired into
    // `zig build test`.
    //
    // Path note (ci-pipelines-green): the wrapper is shipped INSIDE the
    // botopink-lang tree so `zig build test-libs` works in both the meta
    // workspace layout (`<meta>/repository/botopink-lang/`) and the
    // standalone lib-checkout layout (`<lib>/botopink-lang/`) without the
    // sibling lib workflows needing extra steps to stage it.
    const test_libs_run = b.addSystemCommand(&.{ "bash", "scripts/test-libs.sh" });
    test_libs_run.step.dependOn(b.getInstallStep());
    test_libs_run.setCwd(b.path("."));
    test_libs_run.has_side_effects = true; // spawns child compilers — never cache
    if (b.args) |args| test_libs_run.addArgs(args);

    const test_libs_step = b.step("test-libs", "Run every libs/ project's tests per backend");
    test_libs_step.dependOn(&test_libs_run.step);

    // `zig build test-vscode` — run the VS Code extension's pure-function
    // unit suite (`npm test` → tsc typecheck + Node's built-in test runner)
    // through `scripts/test-vscode.sh`, which locates the sibling
    // `vscode-extension` checkout (BOTOPINK_VSCODE_DIR, else
    // `<ancestor>/repository/vscode-extension`) and fails when it cannot. On
    // first run the wrapper does an `npm ci`. NOT wired into `zig build test` —
    // needs `node`/`npm` and a sibling checkout.
    const test_vscode_run = b.addSystemCommand(&.{ "bash", "scripts/test-vscode.sh" });
    test_vscode_run.setCwd(b.path("."));
    test_vscode_run.has_side_effects = true; // spawns node — never cache

    const test_vscode_step = b.step("test-vscode", "Run the VS Code extension unit tests");
    test_vscode_step.dependOn(&test_vscode_run.step);

    // `zig build test-language` — the language tests of decision 8 (front 15):
    // `case` and patterns, tuples and labels, `loop`, written in botopink under
    // `tests/language/` and run by `tests/language/run.sh` on commonJS and
    // erlang against the installed `botopink`, with the expected failures in
    // `tests/language/expected-failures.txt`. Forwards `--` args, e.g.
    //   zig build test-language -- --target erlang --compiler <botopink>
    // NOT wired into `zig build test` (spawns node/erl per file).
    const test_language_run = b.addSystemCommand(&.{ "bash", "tests/language/run.sh" });
    test_language_run.step.dependOn(b.getInstallStep());
    test_language_run.setCwd(b.path("."));
    test_language_run.has_side_effects = true; // spawns child compilers — never cache
    if (b.args) |args| test_language_run.addArgs(args);

    const test_language_step = b.step("test-language", "Run the botopink language tests (tests/language)");
    test_language_step.dependOn(&test_language_run.step);

    // `zig build test-docs` — every `botopink` fence of the user docs compiles
    // (front 14 step 3). `scripts/check-docs.sh` extracts each fence into a
    // scratch project and runs `botopink check`; a fence that is a table rather
    // than a module carries a `<!-- docs-check: skip <reason> -->` comment.
    // Forwards `--` args, e.g.
    //   zig build test-docs -- --doc docs.md --list
    // NOT wired into `zig build test` (spawns a compiler per fence).
    const test_docs_run = b.addSystemCommand(&.{ "bash", "scripts/check-docs.sh" });
    test_docs_run.step.dependOn(b.getInstallStep());
    test_docs_run.setCwd(b.path("."));
    test_docs_run.has_side_effects = true; // spawns child compilers — never cache
    if (b.args) |args| test_docs_run.addArgs(args);

    const test_docs_step = b.step("test-docs", "Compile every botopink fence in the user docs");
    test_docs_step.dependOn(&test_docs_run.step);

    // `zig build test-backends` — the single build step that reaches BEAM + wasm
    // *execution* (not just codegen snapshots): builds the CLI, then runs the
    // backend-execution harness against `node`/`escript`/`erlc`+`erl`/`wasmtime`,
    // skipping any backend whose runtime is absent. Every cell is a hard assert.
    // Like `test-libs`/`test-vscode` it is NOT wired into `zig build test` (needs
    // those runtimes on PATH). BOTOPINK_SKIP_BUILD=1 avoids nesting a `zig
    // build` — the CLI is installed by the dependency below.
    const test_backends_run = cliScript(b, "backend_exec.sh");
    const test_backends_step = b.step("test-backends", "Run beam/wasm/erlang execution parity scenarios");
    test_backends_step.dependOn(&test_backends_run.step);

    // `zig build test-cli` — every end-to-end CLI script under
    // `modules/compiler-cli/tests/`, each against the installed binary
    // (BOTOPINK_SKIP_BUILD=1): the command contract (`cli_contract.sh`), the
    // `botopink test` behaviours (`test_tooling.sh`), forward references and
    // mutual recursion on every backend (`mutual_recursion.sh`), and backend
    // execution parity (`backend_exec.sh`, also `test-backends`). The scripts
    // run one after another — they share `zig-out/` and fixture `out/` dirs.
    const cli_scripts = [_][]const u8{ "cli_contract.sh", "test_tooling.sh", "mutual_recursion.sh", "backend_exec.sh" };
    const test_cli_step = b.step("test-cli", "Run every modules/compiler-cli/tests/*.sh against the installed CLI");
    var prev_cli_script: ?*std.Build.Step = null;
    for (cli_scripts) |script| {
        const run_script = cliScript(b, script);
        if (prev_cli_script) |p| run_script.step.dependOn(p);
        prev_cli_script = &run_script.step;
        test_cli_step.dependOn(&run_script.step);
    }

    // ── compiler-web: compiler-core for the browser (front 18 step 5) ─────────
    // `zig build compiler-web` → zig-out/web/{botopink.wasm, glue.js, index.html}.
    // A `wasm32-wasi` build of compiler-core's API (`modules/compiler-web/src/
    // web_root.zig`: sources in, generated text out); the target is fixed here,
    // not read from `-Dtarget`, because nothing else in this workspace builds
    // for wasm and the CLI never will (it spawns processes). WASI provides the
    // clock, stdout/stderr and randomness through the JS shim in `glue.js`;
    // the comptime runtime and the RUN LOG executors are compiled out on wasm
    // (`comptime/runtime/runtime.zig`), so the module imports no process spawn.
    // `-Doptimize` applies; the size budget is measured at ReleaseSmall.
    const web_target = b.resolveTargetQuery(.{ .cpu_arch = .wasm32, .os_tag = .wasi });
    const web_core_mod = b.createModule(.{
        .root_source_file = b.path("modules/compiler-core/src/root.zig"),
        .target = web_target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "std_prelude", .module = stdPreludeModule(b, web_target, std_pkg_files, pkg_table_file) },
        },
    });
    web_core_mod.addAnonymousImport("bp_wat_rt.wasm", .{ .root_source_file = wat_rt.getEmittedBin() });
    const web_exe = b.addExecutable(.{
        .name = "botopink",
        .root_module = b.createModule(.{
            .root_source_file = b.path("modules/compiler-web/src/web_root.zig"),
            .target = web_target,
            .optimize = optimize,
            .imports = &.{
                .{ .name = "botopink", .module = web_core_mod },
            },
        }),
    });
    web_exe.entry = .disabled; // a library of exports, not a `_start` program
    web_exe.rdynamic = true; // keep every `export fn` in the wasm export table
    const web_install = b.addInstallArtifact(web_exe, .{ .dest_dir = .{ .override = .{ .custom = "web" } } });
    const web_step = b.step("compiler-web", "Build compiler-core for the browser (zig-out/web/)");
    web_step.dependOn(&web_install.step);
    web_step.dependOn(&b.addInstallFile(b.path("modules/compiler-web/glue.js"), "web/glue.js").step);
    web_step.dependOn(&b.addInstallFile(b.path("modules/compiler-web/index.html"), "web/index.html").step);

    // `zig build test-web` — the browser build answers like the native compiler:
    // `modules/compiler-web/tests/smoke.js` loads `glue.js` and the built
    // module under node, compiles one program to the four targets, and pins a
    // rendered diagnostic and the comptime refusal. Needs `node`; NOT wired
    // into `zig build test` (a wasm build is 15–50 s on top of the suite).
    const test_web_run = b.addSystemCommand(&.{ "node", "modules/compiler-web/tests/smoke.js" });
    test_web_run.addFileArg(web_exe.getEmittedBin());
    test_web_run.setCwd(b.path("."));
    test_web_run.has_side_effects = true; // spawns node — never cache
    const test_web_step = b.step("test-web", "Run the browser build's smoke test under node");
    test_web_step.dependOn(&test_web_run.step);

    // ── Run step ──────────────────────────────────────────────────────────────

    const run_cmd = b.addRunArtifact(cli_exe);
    run_cmd.step.dependOn(b.getInstallStep());
    if (b.args) |args| run_cmd.addArgs(args);

    const run_step = b.step("run", "Build and run the botopink CLI");
    run_step.dependOn(&run_cmd.step);
}

/// A `bash modules/compiler-cli/tests/<script>` run against the installed CLI.
fn cliScript(b: *std.Build, script: []const u8) *std.Build.Step.Run {
    const run = b.addSystemCommand(&.{ "bash", b.fmt("modules/compiler-cli/tests/{s}", .{script}) });
    run.setCwd(b.path("."));
    run.setEnvironmentVariable("BOTOPINK_SKIP_BUILD", "1");
    run.step.dependOn(b.getInstallStep());
    run.has_side_effects = true; // spawns child runtimes — never cache
    return run;
}

/// The `std_prelude` module for one target: the stdlib prelude with the core
/// controller files and the generated "std" package registry embedded. Built
/// for the build target (compiler-core) and again for the host (the resident
/// renderer, which runs during the build).
fn stdPreludeModule(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
    std_pkg_files: []const []const u8,
    pkg_table_file: std.Build.LazyPath,
) *std.Build.Module {
    const std_prelude = b.createModule(.{
        .root_source_file = b.path("modules/compiler-core/src/comptime/stdlib/prelude.zig"),
        .target = target,
    });

    // Core controller files flattened into the global type env. These are NOT
    // importable "std" packages — `prelude.zig` embeds them by name, so they are
    // anonymous imports on the std_prelude module.
    const std_core_files = [_][]const u8{
        "primitives.bp",
        "builtins.d.bp",
        "builtins_fns.d.bp",
    };
    for (std_core_files) |f| {
        std_prelude.addAnonymousImport(f, .{
            .root_source_file = b.path(b.fmt("libs/std/src/{s}", .{f})),
        });
    }

    // The generated registry lives in its own module so its `@embedFile`s
    // resolve against the package `.bp` anonymous imports; `std_prelude`
    // re-exports the table for compiler-core to consume.
    const std_pkg = b.createModule(.{
        .root_source_file = pkg_table_file,
        .target = target,
    });
    for (std_pkg_files) |f| {
        std_pkg.addAnonymousImport(f, .{
            .root_source_file = b.path(b.fmt("libs/std/src/{s}", .{f})),
        });
    }
    for (bundledPkgFiles(b)) |pkg| {
        for (pkg.files) |f| {
            std_pkg.addAnonymousImport(b.fmt("{s}/{s}", .{ pkg.name, f }), .{
                .root_source_file = b.path(b.fmt("libs/{s}/{s}{s}", .{ pkg.name, pkg.src, f })),
            });
        }
    }
    std_prelude.addImport("std_pkg", std_pkg);
    return std_prelude;
}

/// Re-resolve the user-requested target with an explicit bundled-glibc version
/// when the resolved native target points at a `linux-gnu` system. This sidesteps
/// the Zig 0.16 + glibc ≥ 2.41 `.sframe` crt1.o relocation bug by making Zig
/// emit its own crt files instead of dragging the system ones. macOS, Windows,
/// musl and any explicitly-pinned target pass through unchanged.
fn libcResolvedTarget(b: *std.Build, requested: std.Build.ResolvedTarget) std.Build.ResolvedTarget {
    const r = requested.result;
    if (r.os.tag != .linux) return requested;
    if (r.abi != .gnu) return requested;
    var q = requested.query;
    if (q.glibc_version != null) return requested;
    q.glibc_version = .{ .major = 2, .minor = 38, .patch = 0 };
    return b.resolveTargetQuery(q);
}

/// The bundled packages besides `std` (decisions 115–117) — the ONE list of
/// their names in the toolchain. compiler-core, the CLI and the language server
/// read them from the generated `bundled_packages` table, never by name.
const bundled_packages = [_][]const u8{ "std", "routing", "actions" };

const BundledPkg = struct { name: []const u8, src: []const u8, files: []const []const u8 };

/// Each bundled package other than `std`, with its `botopink.json` `src` and
/// `files`. Panics when the manifest is missing, its `name` is not the
/// package's, or a `files` entry is not a `.bp` (decision 117 rule 8).
fn bundledPkgFiles(b: *std.Build) []const BundledPkg {
    var out: std.ArrayListUnmanaged(BundledPkg) = .empty;
    for (bundled_packages) |name| {
        if (std.mem.eql(u8, name, "std")) continue;
        const path = b.fmt("libs/{s}/botopink.json", .{name});
        const text = b.build_root.handle.readFileAlloc(b.graph.io, path, b.allocator, .unlimited) catch |err|
            std.debug.panic("bundled package `{s}`: cannot read {s}: {s}", .{ name, path, @errorName(err) });
        const parsed = std.json.parseFromSliceLeaky(std.json.Value, b.allocator, text, .{}) catch |err|
            std.debug.panic("bundled package `{s}`: {s} is not JSON: {s}", .{ name, path, @errorName(err) });
        const obj = parsed.object;
        const declared = if (obj.get("name")) |v| v.string else "";
        if (!std.mem.eql(u8, declared, name)) std.debug.panic(
            "bundled package `{s}`: {s} declares \"name\": \"{s}\"",
            .{ name, path, declared },
        );
        var src: []const u8 = if (obj.get("src")) |v| v.string else "src/";
        if (src.len > 0 and src[src.len - 1] != '/') src = b.fmt("{s}/", .{src});
        const files_val = obj.get("files") orelse std.debug.panic("bundled package `{s}`: {s} has no `files`", .{ name, path });
        var files: std.ArrayListUnmanaged([]const u8) = .empty;
        for (files_val.array.items) |f| {
            if (!std.mem.endsWith(u8, f.string, ".bp") or std.mem.endsWith(u8, f.string, ".d.bp")) std.debug.panic(
                "bundled package `{s}`: `files` entry \"{s}\" is not a `.bp` module — a bundled library ships `.bp` files only (decision 117 rule 8)",
                .{ name, f.string },
            );
            files.append(b.allocator, f.string) catch @panic("OOM");
        }
        out.append(b.allocator, .{ .name = name, .src = src, .files = files.items }) catch @panic("OOM");
    }
    return out.items;
}

/// Derive the importable "std" package module files from the std module tree
/// (`libs/std/src/root.bp`), the way the CLI resolver follows a package's
/// `mod` declarations: each `mod X;` / `pub mod X;` of a declaring file names
/// `X.bp` (a sibling) or `X/mod.bp` (a folder index) in that file's directory
/// — exactly one must exist — and a folder index is followed in turn, so
/// `pub mod io;` embeds `io/fs.bp`, `io/http.bp`, … under the paths `io/fs`,
/// `io/http` (decision 106's tree). Files are relative to `libs/std/src`, in
/// declaration order, depth-first. This keeps `root.bp` the single source of
/// truth for the std module set. Panics with a clear message if the root is
/// missing, declares nothing, or a `mod` resolves to neither or both of its
/// two spellings — a misread here would silently drop std modules and break
/// every build.
fn stdPkgFilesFromRoot(b: *std.Build) []const []const u8 {
    var files: std.ArrayListUnmanaged([]const u8) = .empty;
    collectStdModules(b, &files, "root.bp", "");
    if (files.items.len == 0) std.debug.panic(
        "std pilot: libs/std/src/root.bp declares no `pub mod` modules",
        .{},
    );
    return files.toOwnedSlice(b.allocator) catch @panic("OOM");
}

/// One declaring file of the std tree: `decl_file` relative to `libs/std/src`
/// (`root.bp`, `io/mod.bp`), `prefix` the module-path prefix its `mod`s live
/// under (`""`, `"io/"`).
fn collectStdModules(
    b: *std.Build,
    files: *std.ArrayListUnmanaged([]const u8),
    decl_file: []const u8,
    prefix: []const u8,
) void {
    const decl_path = b.fmt("libs/std/src/{s}", .{decl_file});
    const src = b.build_root.handle.readFileAlloc(
        b.graph.io,
        decl_path,
        b.allocator,
        .unlimited,
    ) catch |err| std.debug.panic(
        "std pilot: cannot read {s} (a std module-tree file): {s}",
        .{ decl_path, @errorName(err) },
    );

    var it = std.mem.splitScalar(u8, src, '\n');
    while (it.next()) |raw| {
        var line = std.mem.trim(u8, raw, " \t\r");
        // Skip comments and blank lines; accept `mod X;` and `pub mod X;`.
        if (std.mem.startsWith(u8, line, "//")) continue;
        if (std.mem.startsWith(u8, line, "pub ")) line = std.mem.trimStart(u8, line["pub ".len..], " \t");
        if (!std.mem.startsWith(u8, line, "mod ")) continue;
        var name = std.mem.trim(u8, line["mod ".len..], " \t");
        name = std.mem.trimEnd(u8, name, ";");
        name = std.mem.trim(u8, name, " \t");
        if (name.len == 0) continue;

        const sibling = b.fmt("{s}{s}.bp", .{ prefix, name });
        const folder = b.fmt("{s}{s}/mod.bp", .{ prefix, name });
        const has_sibling = stdSrcExists(b, sibling);
        const has_folder = stdSrcExists(b, folder);
        if (has_sibling and has_folder) std.debug.panic(
            "std pilot: `mod {s};` in {s} is ambiguous — both libs/std/src/{s} and libs/std/src/{s} exist",
            .{ name, decl_path, sibling, folder },
        );
        if (!has_sibling and !has_folder) std.debug.panic(
            "std pilot: `mod {s};` in {s} resolves to nothing — neither libs/std/src/{s} nor libs/std/src/{s} exists",
            .{ name, decl_path, sibling, folder },
        );
        if (has_sibling) {
            files.append(b.allocator, sibling) catch @panic("OOM");
        } else {
            collectStdModules(b, files, folder, b.fmt("{s}{s}/", .{ prefix, name }));
        }
    }
}

fn stdSrcExists(b: *std.Build, rel: []const u8) bool {
    b.build_root.handle.access(b.graph.io, b.fmt("libs/std/src/{s}", .{rel}), .{}) catch return false;
    return true;
}
