/// Compile-time string constants for the stdlib .bp source files.
/// Imported by the botopink core type checker to preload primitive interfaces.
/// The .bp/.d.bp sources stay under libs/std/src/ (which is .bp-only); each
/// file is exposed as an anonymous import in build.zig (std_bp_files) and
/// embedded here by name. One `pub const` per stdlib source.
///
/// `primitives.bp` is the controller (numeric tower, Bool, String, Function,
/// Array<T>) and `builtins.d.bp` holds the builtin model (reflection, io, Result,
/// the generators, async, Expr<E>, annotations). Both flatten
/// into the global env. The remaining files are concrete `record`/`enum` modules
/// importable via `import {…} from "std";`.
pub const primitives = @embedFile("primitives.bp");
pub const builtins = @embedFile("builtins.d.bp");

/// `builtins_fns.d.bp` carries the parseable fn-decl slice of `builtins.d.bp`
/// (todo / panic / trap / emit / module / getContext / field) so
/// `registerStdlib` can install them in the global env. Splitting them out
/// keeps the synthetic-interface declarations (Result / Future / Generator /
/// ResultGenerator / FutureGenerator / Context) in `builtins.d.bp` doc-only — those
/// types are pre-registered by `Env.registerBuiltins`, so re-parsing them
/// would red on duplicate type registration.
pub const builtin_fns = @embedFile("builtins_fns.d.bp");

// "std" package impl modules — importable via `import {…} from "std";`.
// These are NOT flattened into the global env (see comptime.zig std_pkg_modules).
// NOTE: `option`/`result` are NOT modules — they are builtin namespaces lowered
// inline by every backend (see comptime/infer.zig `inferBuiltinNamespaceCall`).
//
// The package registry is DATA-DRIVEN: `build.zig` enumerates the package `.bp`
// files (its `std_pkg_files` list) and generates the `pkg_modules` table, which
// this prelude re-exports. compiler-core therefore names no individual std
// module — adding one touches only `build.zig` + `libs/std/`, never this tree.
pub const pkg_modules = @import("std_pkg").pkg_modules;

// Non-std libs are NOT embedded here: `std` is the one lib the core may name.
// Any other lib (a framework, …) is supplied as ordinary input `.bp` modules by
// the driver and resolved generically through the shared import registry — the
// core knows nothing about any specific framework.

// The bundled packages (decisions 115–117): `std` and the libraries shipped
// inside the compiler, importable by name with no `dependencies` entry. The
// list is generated by `build.zig` (its `bundled_packages` constant, the one
// place a name is spelled); each non-std entry carries its `.bp` modules.
pub const BundledPackage = @import("std_pkg").BundledPackage;
pub const bundled_packages = @import("std_pkg").bundled_packages;
