//! The BEAM opcode table `beam_file.zig` assembles against — **generated, do not edit**.
//!
//! Pinned to **Erlang/OTP 28** (decision 86: CI's floor), read off that release's
//! `lib/compiler/src/genop.tab` (`BEAM_FORMAT_NUMBER=0`, 184 opcodes) by
//! `gen_opcodes.sh` beside this file, which also cross-checks every row against the
//! installed `beam_opcodes:opname/1`. Numbers are stable across releases — a release
//! only appends — so a module that uses only opcodes at or below a release's highest
//! loads on that release and every later one; the `Code` chunk's `opcode_max` is the
//! loader's version check.
//!
//! `since` is the release an opcode appeared in (0 = predates the OTP numbering, R5–R17);
//! `obsolete` marks the ones `genop.tab` lists with a leading `-`, which no current
//! loader accepts. `emittable` is decision 86's subset: not obsolete, and present since
//! OTP `stable_floor` (24) — what the assembler refuses to write outside of.

/// The release whose `genop.tab` this table is.
pub const otp_release: u16 = 28;
/// `BEAM_FORMAT_NUMBER` — the `Code` chunk's instruction-set word.
pub const format_number: u32 = 0;
/// The highest opcode of the pinned release.
pub const opcode_max: u8 = 184;
/// Decision 86: the assembler emits only opcodes present since this release.
pub const stable_floor: u8 = 24;

pub const Info = struct {
    name: []const u8,
    arity: u8,
    /// OTP release the opcode appeared in; 0 for the pre-OTP-20 core.
    since: u8,
    obsolete: bool,
};

/// One variant per opcode of the pinned release, valued by its number.
pub const Op = enum(u8) {
    label = 1,
    func_info = 2,
    int_code_end = 3,
    call = 4,
    call_last = 5,
    call_only = 6,
    call_ext = 7,
    call_ext_last = 8,
    bif0 = 9,
    bif1 = 10,
    bif2 = 11,
    allocate = 12,
    allocate_heap = 13,
    allocate_zero = 14,
    allocate_heap_zero = 15,
    test_heap = 16,
    init = 17,
    deallocate = 18,
    @"return" = 19,
    send = 20,
    remove_message = 21,
    timeout = 22,
    loop_rec = 23,
    loop_rec_end = 24,
    wait = 25,
    wait_timeout = 26,
    m_plus = 27,
    m_minus = 28,
    m_times = 29,
    m_div = 30,
    int_div = 31,
    int_rem = 32,
    int_band = 33,
    int_bor = 34,
    int_bxor = 35,
    int_bsl = 36,
    int_bsr = 37,
    int_bnot = 38,
    is_lt = 39,
    is_ge = 40,
    is_eq = 41,
    is_ne = 42,
    is_eq_exact = 43,
    is_ne_exact = 44,
    is_integer = 45,
    is_float = 46,
    is_number = 47,
    is_atom = 48,
    is_pid = 49,
    is_reference = 50,
    is_port = 51,
    is_nil = 52,
    is_binary = 53,
    is_constant = 54,
    is_list = 55,
    is_nonempty_list = 56,
    is_tuple = 57,
    test_arity = 58,
    select_val = 59,
    select_tuple_arity = 60,
    jump = 61,
    @"catch" = 62,
    catch_end = 63,
    move = 64,
    get_list = 65,
    get_tuple_element = 66,
    set_tuple_element = 67,
    put_string = 68,
    put_list = 69,
    put_tuple = 70,
    put = 71,
    badmatch = 72,
    if_end = 73,
    case_end = 74,
    call_fun = 75,
    make_fun = 76,
    is_function = 77,
    call_ext_only = 78,
    bs_start_match = 79,
    bs_get_integer = 80,
    bs_get_float = 81,
    bs_get_binary = 82,
    bs_skip_bits = 83,
    bs_test_tail = 84,
    bs_save = 85,
    bs_restore = 86,
    bs_init = 87,
    bs_final = 88,
    bs_put_integer = 89,
    bs_put_binary = 90,
    bs_put_float = 91,
    bs_put_string = 92,
    bs_need_buf = 93,
    fclearerror = 94,
    fcheckerror = 95,
    fmove = 96,
    fconv = 97,
    fadd = 98,
    fsub = 99,
    fmul = 100,
    fdiv = 101,
    fnegate = 102,
    make_fun2 = 103,
    @"try" = 104,
    try_end = 105,
    try_case = 106,
    try_case_end = 107,
    raise = 108,
    bs_init2 = 109,
    bs_bits_to_bytes = 110,
    bs_add = 111,
    apply = 112,
    apply_last = 113,
    is_boolean = 114,
    is_function2 = 115,
    bs_start_match2 = 116,
    bs_get_integer2 = 117,
    bs_get_float2 = 118,
    bs_get_binary2 = 119,
    bs_skip_bits2 = 120,
    bs_test_tail2 = 121,
    bs_save2 = 122,
    bs_restore2 = 123,
    gc_bif1 = 124,
    gc_bif2 = 125,
    bs_final2 = 126,
    bs_bits_to_bytes2 = 127,
    put_literal = 128,
    is_bitstr = 129,
    bs_context_to_binary = 130,
    bs_test_unit = 131,
    bs_match_string = 132,
    bs_init_writable = 133,
    bs_append = 134,
    bs_private_append = 135,
    trim = 136,
    bs_init_bits = 137,
    bs_get_utf8 = 138,
    bs_skip_utf8 = 139,
    bs_get_utf16 = 140,
    bs_skip_utf16 = 141,
    bs_get_utf32 = 142,
    bs_skip_utf32 = 143,
    bs_utf8_size = 144,
    bs_put_utf8 = 145,
    bs_utf16_size = 146,
    bs_put_utf16 = 147,
    bs_put_utf32 = 148,
    on_load = 149,
    recv_mark = 150,
    recv_set = 151,
    gc_bif3 = 152,
    line = 153,
    put_map_assoc = 154,
    put_map_exact = 155,
    is_map = 156,
    has_map_fields = 157,
    get_map_elements = 158,
    is_tagged_tuple = 159,
    build_stacktrace = 160,
    raw_raise = 161,
    get_hd = 162,
    get_tl = 163,
    put_tuple2 = 164,
    bs_get_tail = 165,
    bs_start_match3 = 166,
    bs_get_position = 167,
    bs_set_position = 168,
    swap = 169,
    bs_start_match4 = 170,
    make_fun3 = 171,
    init_yregs = 172,
    recv_marker_bind = 173,
    recv_marker_clear = 174,
    recv_marker_reserve = 175,
    recv_marker_use = 176,
    bs_create_bin = 177,
    call_fun2 = 178,
    nif_start = 179,
    badrecord = 180,
    update_record = 181,
    bs_match = 182,
    executable_line = 183,
    debug_line = 184,

    pub fn info(self: Op) Info {
        return table[@intFromEnum(self)];
    }

    /// Decision 86's subset: not obsolete, present since `stable_floor`.
    pub fn emittable(self: Op) bool {
        const i = self.info();
        return !i.obsolete and i.since <= stable_floor;
    }
};

/// Indexed by opcode number; index 0 is unused.
pub const table = [_]Info{
    .{ .name = "", .arity = 0, .since = 0, .obsolete = true },
    .{ .name = "label", .arity = 1, .since = 0, .obsolete = false },
    .{ .name = "func_info", .arity = 3, .since = 0, .obsolete = false },
    .{ .name = "int_code_end", .arity = 0, .since = 0, .obsolete = false },
    .{ .name = "call", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "call_last", .arity = 3, .since = 0, .obsolete = false },
    .{ .name = "call_only", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "call_ext", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "call_ext_last", .arity = 3, .since = 0, .obsolete = false },
    .{ .name = "bif0", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "bif1", .arity = 4, .since = 0, .obsolete = false },
    .{ .name = "bif2", .arity = 5, .since = 0, .obsolete = false },
    .{ .name = "allocate", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "allocate_heap", .arity = 3, .since = 0, .obsolete = false },
    .{ .name = "allocate_zero", .arity = 2, .since = 0, .obsolete = true },
    .{ .name = "allocate_heap_zero", .arity = 3, .since = 0, .obsolete = true },
    .{ .name = "test_heap", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "init", .arity = 1, .since = 0, .obsolete = true },
    .{ .name = "deallocate", .arity = 1, .since = 0, .obsolete = false },
    .{ .name = "return", .arity = 0, .since = 0, .obsolete = false },
    .{ .name = "send", .arity = 0, .since = 0, .obsolete = false },
    .{ .name = "remove_message", .arity = 0, .since = 0, .obsolete = false },
    .{ .name = "timeout", .arity = 0, .since = 0, .obsolete = false },
    .{ .name = "loop_rec", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "loop_rec_end", .arity = 1, .since = 0, .obsolete = false },
    .{ .name = "wait", .arity = 1, .since = 0, .obsolete = false },
    .{ .name = "wait_timeout", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "m_plus", .arity = 4, .since = 0, .obsolete = true },
    .{ .name = "m_minus", .arity = 4, .since = 0, .obsolete = true },
    .{ .name = "m_times", .arity = 4, .since = 0, .obsolete = true },
    .{ .name = "m_div", .arity = 4, .since = 0, .obsolete = true },
    .{ .name = "int_div", .arity = 4, .since = 0, .obsolete = true },
    .{ .name = "int_rem", .arity = 4, .since = 0, .obsolete = true },
    .{ .name = "int_band", .arity = 4, .since = 0, .obsolete = true },
    .{ .name = "int_bor", .arity = 4, .since = 0, .obsolete = true },
    .{ .name = "int_bxor", .arity = 4, .since = 0, .obsolete = true },
    .{ .name = "int_bsl", .arity = 4, .since = 0, .obsolete = true },
    .{ .name = "int_bsr", .arity = 4, .since = 0, .obsolete = true },
    .{ .name = "int_bnot", .arity = 3, .since = 0, .obsolete = true },
    .{ .name = "is_lt", .arity = 3, .since = 0, .obsolete = false },
    .{ .name = "is_ge", .arity = 3, .since = 0, .obsolete = false },
    .{ .name = "is_eq", .arity = 3, .since = 0, .obsolete = false },
    .{ .name = "is_ne", .arity = 3, .since = 0, .obsolete = false },
    .{ .name = "is_eq_exact", .arity = 3, .since = 0, .obsolete = false },
    .{ .name = "is_ne_exact", .arity = 3, .since = 0, .obsolete = false },
    .{ .name = "is_integer", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "is_float", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "is_number", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "is_atom", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "is_pid", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "is_reference", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "is_port", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "is_nil", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "is_binary", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "is_constant", .arity = 2, .since = 0, .obsolete = true },
    .{ .name = "is_list", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "is_nonempty_list", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "is_tuple", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "test_arity", .arity = 3, .since = 0, .obsolete = false },
    .{ .name = "select_val", .arity = 3, .since = 0, .obsolete = false },
    .{ .name = "select_tuple_arity", .arity = 3, .since = 0, .obsolete = false },
    .{ .name = "jump", .arity = 1, .since = 0, .obsolete = false },
    .{ .name = "catch", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "catch_end", .arity = 1, .since = 0, .obsolete = false },
    .{ .name = "move", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "get_list", .arity = 3, .since = 0, .obsolete = false },
    .{ .name = "get_tuple_element", .arity = 3, .since = 0, .obsolete = false },
    .{ .name = "set_tuple_element", .arity = 3, .since = 0, .obsolete = false },
    .{ .name = "put_string", .arity = 3, .since = 0, .obsolete = true },
    .{ .name = "put_list", .arity = 3, .since = 0, .obsolete = false },
    .{ .name = "put_tuple", .arity = 2, .since = 0, .obsolete = true },
    .{ .name = "put", .arity = 1, .since = 0, .obsolete = true },
    .{ .name = "badmatch", .arity = 1, .since = 0, .obsolete = false },
    .{ .name = "if_end", .arity = 0, .since = 0, .obsolete = false },
    .{ .name = "case_end", .arity = 1, .since = 0, .obsolete = false },
    .{ .name = "call_fun", .arity = 1, .since = 0, .obsolete = false },
    .{ .name = "make_fun", .arity = 3, .since = 0, .obsolete = true },
    .{ .name = "is_function", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "call_ext_only", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "bs_start_match", .arity = 2, .since = 0, .obsolete = true },
    .{ .name = "bs_get_integer", .arity = 5, .since = 0, .obsolete = true },
    .{ .name = "bs_get_float", .arity = 5, .since = 0, .obsolete = true },
    .{ .name = "bs_get_binary", .arity = 5, .since = 0, .obsolete = true },
    .{ .name = "bs_skip_bits", .arity = 4, .since = 0, .obsolete = true },
    .{ .name = "bs_test_tail", .arity = 2, .since = 0, .obsolete = true },
    .{ .name = "bs_save", .arity = 1, .since = 0, .obsolete = true },
    .{ .name = "bs_restore", .arity = 1, .since = 0, .obsolete = true },
    .{ .name = "bs_init", .arity = 2, .since = 0, .obsolete = true },
    .{ .name = "bs_final", .arity = 2, .since = 0, .obsolete = true },
    .{ .name = "bs_put_integer", .arity = 5, .since = 0, .obsolete = true },
    .{ .name = "bs_put_binary", .arity = 5, .since = 0, .obsolete = true },
    .{ .name = "bs_put_float", .arity = 5, .since = 0, .obsolete = true },
    .{ .name = "bs_put_string", .arity = 2, .since = 0, .obsolete = true },
    .{ .name = "bs_need_buf", .arity = 1, .since = 0, .obsolete = true },
    .{ .name = "fclearerror", .arity = 0, .since = 0, .obsolete = true },
    .{ .name = "fcheckerror", .arity = 1, .since = 0, .obsolete = true },
    .{ .name = "fmove", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "fconv", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "fadd", .arity = 4, .since = 0, .obsolete = false },
    .{ .name = "fsub", .arity = 4, .since = 0, .obsolete = false },
    .{ .name = "fmul", .arity = 4, .since = 0, .obsolete = false },
    .{ .name = "fdiv", .arity = 4, .since = 0, .obsolete = false },
    .{ .name = "fnegate", .arity = 3, .since = 0, .obsolete = false },
    .{ .name = "make_fun2", .arity = 1, .since = 0, .obsolete = true },
    .{ .name = "try", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "try_end", .arity = 1, .since = 0, .obsolete = false },
    .{ .name = "try_case", .arity = 1, .since = 0, .obsolete = false },
    .{ .name = "try_case_end", .arity = 1, .since = 0, .obsolete = false },
    .{ .name = "raise", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "bs_init2", .arity = 6, .since = 0, .obsolete = true },
    .{ .name = "bs_bits_to_bytes", .arity = 3, .since = 0, .obsolete = true },
    .{ .name = "bs_add", .arity = 5, .since = 0, .obsolete = true },
    .{ .name = "apply", .arity = 1, .since = 0, .obsolete = false },
    .{ .name = "apply_last", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "is_boolean", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "is_function2", .arity = 3, .since = 0, .obsolete = false },
    .{ .name = "bs_start_match2", .arity = 5, .since = 0, .obsolete = true },
    .{ .name = "bs_get_integer2", .arity = 7, .since = 0, .obsolete = false },
    .{ .name = "bs_get_float2", .arity = 7, .since = 0, .obsolete = false },
    .{ .name = "bs_get_binary2", .arity = 7, .since = 0, .obsolete = false },
    .{ .name = "bs_skip_bits2", .arity = 5, .since = 0, .obsolete = false },
    .{ .name = "bs_test_tail2", .arity = 3, .since = 0, .obsolete = false },
    .{ .name = "bs_save2", .arity = 2, .since = 0, .obsolete = true },
    .{ .name = "bs_restore2", .arity = 2, .since = 0, .obsolete = true },
    .{ .name = "gc_bif1", .arity = 5, .since = 0, .obsolete = false },
    .{ .name = "gc_bif2", .arity = 6, .since = 0, .obsolete = false },
    .{ .name = "bs_final2", .arity = 2, .since = 0, .obsolete = true },
    .{ .name = "bs_bits_to_bytes2", .arity = 2, .since = 0, .obsolete = true },
    .{ .name = "put_literal", .arity = 2, .since = 0, .obsolete = true },
    .{ .name = "is_bitstr", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "bs_context_to_binary", .arity = 1, .since = 0, .obsolete = true },
    .{ .name = "bs_test_unit", .arity = 3, .since = 0, .obsolete = false },
    .{ .name = "bs_match_string", .arity = 4, .since = 0, .obsolete = false },
    .{ .name = "bs_init_writable", .arity = 0, .since = 0, .obsolete = false },
    .{ .name = "bs_append", .arity = 8, .since = 0, .obsolete = true },
    .{ .name = "bs_private_append", .arity = 6, .since = 0, .obsolete = true },
    .{ .name = "trim", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "bs_init_bits", .arity = 6, .since = 0, .obsolete = true },
    .{ .name = "bs_get_utf8", .arity = 5, .since = 0, .obsolete = false },
    .{ .name = "bs_skip_utf8", .arity = 4, .since = 0, .obsolete = false },
    .{ .name = "bs_get_utf16", .arity = 5, .since = 0, .obsolete = false },
    .{ .name = "bs_skip_utf16", .arity = 4, .since = 0, .obsolete = false },
    .{ .name = "bs_get_utf32", .arity = 5, .since = 0, .obsolete = false },
    .{ .name = "bs_skip_utf32", .arity = 4, .since = 0, .obsolete = false },
    .{ .name = "bs_utf8_size", .arity = 3, .since = 0, .obsolete = true },
    .{ .name = "bs_put_utf8", .arity = 3, .since = 0, .obsolete = true },
    .{ .name = "bs_utf16_size", .arity = 3, .since = 0, .obsolete = true },
    .{ .name = "bs_put_utf16", .arity = 3, .since = 0, .obsolete = true },
    .{ .name = "bs_put_utf32", .arity = 3, .since = 0, .obsolete = true },
    .{ .name = "on_load", .arity = 0, .since = 0, .obsolete = false },
    .{ .name = "recv_mark", .arity = 1, .since = 0, .obsolete = true },
    .{ .name = "recv_set", .arity = 1, .since = 0, .obsolete = true },
    .{ .name = "gc_bif3", .arity = 7, .since = 0, .obsolete = false },
    .{ .name = "line", .arity = 1, .since = 0, .obsolete = false },
    .{ .name = "put_map_assoc", .arity = 5, .since = 0, .obsolete = false },
    .{ .name = "put_map_exact", .arity = 5, .since = 0, .obsolete = false },
    .{ .name = "is_map", .arity = 2, .since = 0, .obsolete = false },
    .{ .name = "has_map_fields", .arity = 3, .since = 0, .obsolete = false },
    .{ .name = "get_map_elements", .arity = 3, .since = 0, .obsolete = false },
    .{ .name = "is_tagged_tuple", .arity = 4, .since = 20, .obsolete = false },
    .{ .name = "build_stacktrace", .arity = 0, .since = 21, .obsolete = false },
    .{ .name = "raw_raise", .arity = 0, .since = 21, .obsolete = false },
    .{ .name = "get_hd", .arity = 2, .since = 21, .obsolete = false },
    .{ .name = "get_tl", .arity = 2, .since = 21, .obsolete = false },
    .{ .name = "put_tuple2", .arity = 2, .since = 22, .obsolete = false },
    .{ .name = "bs_get_tail", .arity = 3, .since = 22, .obsolete = false },
    .{ .name = "bs_start_match3", .arity = 4, .since = 22, .obsolete = false },
    .{ .name = "bs_get_position", .arity = 3, .since = 22, .obsolete = false },
    .{ .name = "bs_set_position", .arity = 2, .since = 22, .obsolete = false },
    .{ .name = "swap", .arity = 2, .since = 23, .obsolete = false },
    .{ .name = "bs_start_match4", .arity = 4, .since = 23, .obsolete = false },
    .{ .name = "make_fun3", .arity = 3, .since = 24, .obsolete = false },
    .{ .name = "init_yregs", .arity = 1, .since = 24, .obsolete = false },
    .{ .name = "recv_marker_bind", .arity = 2, .since = 24, .obsolete = false },
    .{ .name = "recv_marker_clear", .arity = 1, .since = 24, .obsolete = false },
    .{ .name = "recv_marker_reserve", .arity = 1, .since = 24, .obsolete = false },
    .{ .name = "recv_marker_use", .arity = 1, .since = 24, .obsolete = false },
    .{ .name = "bs_create_bin", .arity = 6, .since = 25, .obsolete = false },
    .{ .name = "call_fun2", .arity = 3, .since = 25, .obsolete = false },
    .{ .name = "nif_start", .arity = 0, .since = 25, .obsolete = false },
    .{ .name = "badrecord", .arity = 1, .since = 25, .obsolete = false },
    .{ .name = "update_record", .arity = 5, .since = 26, .obsolete = false },
    .{ .name = "bs_match", .arity = 3, .since = 26, .obsolete = false },
    .{ .name = "executable_line", .arity = 2, .since = 27, .obsolete = false },
    .{ .name = "debug_line", .arity = 4, .since = 28, .obsolete = false },
};

const std = @import("std");

test "opcodes: the table is dense, numbered by index, and the enum agrees with it" {
    try std.testing.expectEqual(@as(usize, opcode_max + 1), table.len);
    inline for (@typeInfo(Op).@"enum".fields) |f| {
        const op: Op = @enumFromInt(f.value);
        try std.testing.expectEqualStrings(f.name, op.info().name);
    }
    try std.testing.expectEqual(@as(u8, 1), Op.label.info().arity);
    try std.testing.expectEqual(@as(u8, 3), Op.func_info.info().arity);
    try std.testing.expectEqual(@as(u8, 0), Op.int_code_end.info().arity);
}

test "opcodes: the emittable subset is decision 86's" {
    // Present since OTP 24, so in.
    try std.testing.expect(Op.make_fun3.emittable());
    try std.testing.expect(Op.init_yregs.emittable());
    try std.testing.expect(Op.call_ext.emittable());
    // Appeared after the floor, so out — even though the pinned release knows them.
    try std.testing.expect(!Op.bs_create_bin.emittable());
    try std.testing.expect(!Op.update_record.emittable());
    try std.testing.expect(!Op.debug_line.emittable());
    // Obsolete before the floor, so out.
    try std.testing.expect(!Op.allocate_zero.emittable());
    try std.testing.expect(!Op.put_tuple.emittable());
    try std.testing.expect(!Op.fclearerror.emittable());
}
